# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'point2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for point2
  pod 'Alamofire'

  target 'point2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'point2UITests' do
    # Pods for testing
  end

end
